name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr imagemagick ffmpeg libgl1
      - name: Install
        run: pip install -e .[dev]
      - name: Diagnose env
        run: python tools/diagnose_env.py
      - name: Ruff
        run: ruff check .
      - name: Mypy
        run: mypy .
      - name: Pytest
        run: pytest -q --junitxml=tests_report.xml
      - uses: actions/upload-artifact@v4
        with:
          name: junit
          path: tests_report.xml
